### ISSUE TITLE
registerEffect ignores last item in calls array / goes out of order / resets at every step

### ISSUE THREAD

**Issue by PascalPixel** [google-fabric/velocity-react#217]
![velocity](https://user-images.githubusercontent.com/3094044/28313303-584ade56-6bf1-11e7-937d-a5642fe55496.gif)
*Description:* I have an animation that has nine steps, of which 5 are locations visible in the top-down 2D view offered in this GIF. tagging @finneganh and @Rycochet as I don't know what part is causing this...
*Expected:* it should go from A to B C D and E
*Actual:* A B A C A D A E - It might also simply be resetting all styles or have some issue with delay not being put in?

```es6
import React from 'react'
import ReactDOM from 'react-dom'
import { VelocityComponent, velocityHelpers } from 'velocity-react'
require('velocity-animate')
require('velocity-animate/velocity.ui')

const AnimationName = velocityHelpers.registerEffect({
  defaultDuration: 5000,
  calls: [
    [{
      translateX: '10vw',
      translateY: '32.3vw',
      translateZ: '10vw'
    }],
    [{
      translateX: '44.2vw',
      translateY: '39.5vw',
      translateZ: '5vw'
    }],
    [{
      translateX: '44.2vw',
      translateY: '39.5vw',
      translateZ: '0vw'
    }],
    [{
      translateX: '44.2vw',
      translateY: '39.5vw',
      translateZ: '8vw'
    }],
    [{
      translateX: '44.5vw',
      translateY: '58.7vw',
      translateZ: '5vw'
    }],
    [{
      translateX: '64vw',
      translateY: '58vw',
      translateZ: '5vw'
    }],
    [{
      translateX: '64vw',
      translateY: '58vw',
      translateZ: '0vw'
    }],
    [{
      translateX: '64vw',
      translateY: '58vw',
      translateZ: '8vw'
    }],
    [{
      translateX: '64.5vw',
      translateY: '84.6vw',
      translateZ: '0vw'
    }]
  ]
})

class VelocityBug extends React.Component {
  constructor (props) {
    super(props)

    this.state = {
      animationStarted: false
    }
  }

  componentDidMount () {
    window.setTimeout(
      this.setState({
        animationStarted: true
      })
    , 2000)
  }

  render () {
    return (
      <div style={{
        width: '100vw',
        height: '100vw',
        position: 'relative',
        background: 'purple'
      }}>
        <VelocityComponent animation={this.state.animationStarted ? AnimationName : null}>
          <div style={{
            position: 'absolute',
            width: '9vw',
            height: '9vw',
            background: 'orange'
          }} />
        </VelocityComponent>
      </div>
    )
  }
}

ReactDOM.render(<VelocityBug />, document.getElementById('root'))
```

**Comment by Rycochet** [comment]
Try adding a duration percentage to each of the calls - it's 1 by default, so with 9 calls should be 1/9 -

```
  calls: [
    [{
      translateX: '10vw',
      translateY: '32.3vw',
      translateZ: '10vw'
    }, 1/9],
```

If that doesn't sort it out then I don't know - this function itself is going to be changed and replaced in v2 of Velocity, which will hopefully be testing properly by the end of the month...

**Comment by Superpencil** [comment]
Thank you @Rycochet! 
- It fixed starting at 0 every time
- But now the sequence is: 0 ? 1 4 2 3 9, seemingly omitting a few...
I'm starting to think this is related to the same thing last time where things have to be manually declared in-line, but in React this isn't possible... I'll mess around some more.

Can't wait for you to release `v2.0.0-beta` so I can test it ;)

**Comment by Superpencil** [comment]
I think the answer is in prepending of the array @Rycochet - and I believe we talked about it before:

*This array*
```es6
const EmailAnimation = velocityHelpers.registerEffect({
  defaultDuration: 20000,
  calls: [
    [{
      translateX: '10vw',
      translateY: '30vw',
      translateZ: '10vw'
    }, 1 / 3],
    [{
      translateX: '45vw',
      translateY: '40vw',
      translateZ: '5vw'
    }, 1 / 3],
    [{
      translateX: '45vw',
      translateY: '40vw',
      translateZ: '0vw'
    }, 1 / 3]
  ]
})
```
*Results in that the Initial state never registered, so it prepends the array with 0 to the first amounts, and then skips the last step. 

When we found this issue last time with `runSequence`, and the solution was to apply the css inline beforehand, but this isn't possible in react, I hope 2.0 fixes it @Rycochet :)

**Comment by Rycochet** [comment]
I honestly can't remember - but there's nothing stopping you using "real" css values now -

```javascript
const EmailAnimation = velocityHelpers.registerEffect({
  defaultDuration: 20000,
  calls: [
    [{
      transform: 'translate(10vw,30vw,10vw)'
    }, 1 / 3],
    [{
      transform: 'translate(45vw,40vw,5vw)'
    }, 1 / 3],
    [{
      transform: 'translate(45vw,40vw,0vw)'
    }, 1 / 3]
  ]
})
```

The split apart `translateX / Y / Z` etc parts are already removed in v2 (though will be available with a polyfill before release) - not least because you have no control of the order transforms are added when using an Object (alphabetical now btw).

I feel you'll still need to forcefeed the first value simply so the parser has something to work with - spaces are ignored so if that's the only transform on then having `transform:translate(0,0,0);` in the CSS might be enough.

**Comment by Superpencil** [comment]
@Rycochet thank you for your continued comments!
- I attempted to implement your code but it gets ignored by Velocity
- Is this implemented only in `1.5.0`?
- Forcing `velocity-react` to use `velocity-animate@1.5.0` didn't work for me, perhaps I did it wrong.
- Last item in array is always ignored, even with simpler animations, even when attribute of style is declared on the div beforehand (width in this case)
```es6
const TheAnimation = velocityHelpers.registerEffect({
  defaultDuration: 300,
  calls: [
    [{ width: '100px' }, 3 / 1],
    [{ width: '200px' }, 3 / 1],
    [{ width: '100px' }, 3 / 1]
  ]
})
```
Seeing as I can't get this to work, I've opted to attempt to replace velocity for now, fingers crossed!

**Comment by Rycochet** [comment]
It was added in Velocity 1.3.2 (so was working in 1.4.0 as used here). Not sure why it's not working, and sadly not really got the time to look into it with everything else that's changing - though hopefully with v2 things will improve (and as I used React at work occasionally I'm hoping this will fully support it soon after release) ;-)

Definitely sounds like there's some bug there though :-(

**Comment by Superpencil** [comment]
@Rycochet looking forward to your first major release 💯
