### ISSUE TITLE
upgrade to react transition group v2 dependency

### ISSUE THREAD

**Issue by lukeapage** [google-fabric/velocity-react#224]

**Comment by finneganh** [comment]
Any reason why you think that this is important? The v1 branch is still being maintained.

**Comment by lukeapage** [comment]
Ok, sorry I didn't realize that.. if v1 will support react 16 it's not important to me.

**Comment by finneganh** [comment]
Yeah, that's the big question. If not, I'll work on getting this upgraded,
since I want to use 16, too, but working through any timing changes with
the new version RTG implementation will likely be a pain.

**Comment by jquense** [comment]
I'm gonna backport the peer dep range update to v1 but at this point i'd consider v1 deprecated, i have no idea when it is going to stop working and v2 contains a bunch of better stuff that should make implementation easier! let me know if ya'll need info

**Comment by finneganh** [comment]
Ok, I’ll have a look.

We still need a custom TransitionGroup subclass to coordinate transitions
across elements (this lets us use Velocity’s stagger) but I think that the
new API can be adapted to that. The implementation won’t be in the form of
public Transition elements.

**Comment by lhamrit** [comment]
react-transition-group 1.2.1 now supports React 16 ([link](https://github.com/reactjs/react-transition-group/blob/v1.2.1/package.json)), so velocity-react could just upgrade to that

**Comment by lukeapage** [comment]
I just pin the sub dependency in my own package Json and let npm resolve both to 1.2.1

**Comment by finneganh** [comment]
Have you noticed any issues at 1.2? I know at least someone else on here downgraded back to 1.1.

**Comment by lukeapage** [comment]
We have been running 1.2.0 in production without any known problems for several months.
