### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by DrGor** [google-fabric/velocity-react#229]
Could you please update the package.json file with newer version of `react-transition-group` ?
The version 1.2.1 supports React 16.

UPDATE
Noticed that React 16 is supported in `master` branch, so we just need a new release (tag).

**Comment by finneganh** [comment]
Sure, should be able to get this out soon. AFAIK react-transition-group
didn’t make any code changes for 16 support, so the benefit is just
clearing up the peer dependency warnings.

**Comment by ryanwild** [comment]
Any update on upgrading `react-transition-group`? The latest version is at 2.2.1

**Comment by finneganh** [comment]
While I expect to upgrade to the most recent 1.x version to fix the peer
dependency, I would not expect to ever upgrade to 2.x.

I’ve looked into this in the past and as I remember it would require
changing a lot and it wasn’t actually a good fit for how this library
operates. To do Velocity tricks like stagger we need to have a top-level
approach to creating animations.
