### ISSUE TITLE
Unknown plugin "transform-object-rest-spread"

### ISSUE THREAD

**Issue by samhastings** [google-fabric/velocity-react#230]
Importing the velocity-react module is causing the following error:

```
ERROR in ./node_modules/velocity-react/index.js
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/path/to/project/node_modules/velocity-react/.babelrc" at 0, attempted to resolve relative to "/path/to/project/node_modules/velocity-react"
```

Looking in the `node_modules` directory, the expected `babel-plugin-transform-object-rest-spread` directory is indeed missing.

I'm using NPM 5.3.0 and Node 8.0.0.

Here are the dev dependencies from my project’s `package.json`:

```
"autoprefixer": "^7.1.5",
"babel-core": "^6.26.0",
"babel-loader": "^7.1.2",
"babel-preset-env": "^1.6.0",
"babel-preset-react": "^6.24.1",
"css-loader": "^0.28.7",
"html-webpack-plugin": "^2.30.1",
"node-sass": "^4.5.3",
"postcss-loader": "^2.0.8",
"prop-types": "^15.6.0",
"react-router-dom": "^4.2.2",
"sass-loader": "^6.0.6",
"style-loader": "^0.19.0",
"velocity-react": "^1.3.3",
"webpack": "^3.8.0",
"webpack-dev-server": "^2.9.2"
```

I've tried deleting my `node_modules` directory and `package-lock.json` file before running a fresh `npm install` but this hasn’t fixed the issue.

**Comment by finneganh** [comment]
What do you have running that's looking at the project's babelrc?

velocity-react ships from npm transpiled to ES5. You shouldn't need to
re-babel it.

**Comment by samhastings** [comment]
Good question! I really am not sure. I'm using Babel to transpile my own project so I assumed that was looking at velocity-react's .babelrc file. But of course it shouldn't need to do that if your code ships pre-transpiled, which I hadn't considered until you mentioned it.

I'm just using `import 'velocity-react';` to try and animate an element in a React component. Could Babel be recursing into this project and trying to transpile again?

Are there any other troubleshooting steps you could recommend? Appreciate this is now looking more like a support request than an issue, so will take this to StackOverflow if you'd prefer.

**Comment by samhastings** [comment]
OK I was unaware of the `exclude` option in the Webpack Babel Loader config, and that was trying to transpile all my Node modules without my knowledge. Just needed to get it to ignore my `node_modules` directory.

```
// webpack.config.babel.js
rules: [
    {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
            'babel-loader',
        ]
    }
]
```

Closing as this is not an issue!
