### ISSUE TITLE
velocity-animate@^2.0.0 compatibility

### ISSUE THREAD

**Issue by jamesarosen** [google-fabric/velocity-react#251]
velocity-react declares a dependency on `"velocity-animate": "^1.4.0"`.

https://www.npmjs.com/package/velocity-animate has released several 2.0.x versions. Most notably, [2.0.2](https://www.npmjs.com/package/velocity-animate/v/2.0.2) fixes this problem:

> Module not found: Error: Can't resolve 'velocity' in '/path/to/node_modules/velocity-animate'

when you try to do
```js
import Velocity from 'velocity-animate'
import 'velocity-animate/velocity.ui'
```

See https://github.com/julianshapiro/velocity/issues/743#issuecomment-372103588

**Comment by fionawhim** [comment]
Looks like 2.0 is still in beta.
